### ISSUE TITLE
Fatal Exception: kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by Vietvantue** [doublesymmetry/KotlinAudio#37]
I faced this issue when using react-native-track-player, which is utilizing KotlinAudio library:

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property descriptionAdapter has not been initialized
       at com.doublesymmetry.kotlinaudio.notification.NotificationManager$destroy$1.invokeSuspend(NotificationManager.kt:295)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by CDBridger** [comment]
yeah this is been in quite a few versions of it. Could we get a fix please?

**Comment by mpivchev** [comment]
Please describe the steps you did that lead to the crash. Can you reproduce this in the example app?

**Comment by Vietvantue** [comment]
@mpivchev Just curious as to why we don't confirm that the **descriptionAdapter** is initialized before calling its function.

**Comment by Vietvantue** [comment]
Another observation concerning this problem is that it occurs when the app is running in the background.

**Comment by mpivchev** [comment]
> Just curious as to why we don't confirm that the **descriptionAdapter** is initialized before calling its function.

That's definitely something we can do

**Comment by s123121** [comment]
Can confirm, happen 100% whenever users put app in background (with another headless task registered)

**Comment by dcvz** [comment]
Is this issue still present for users?
